# https://taskfile.dev

version: '3'

vars:
  IS_VIRTUAL_CONTAINER: false

tasks:
  default:
    cmds:
      - task open-project
      - task 
    silent: true
  sync-notes:
    cmds:
      - git fetch
  open-project:
    cmds:
      - codium 
    dir: .
  open-notes:
    cmds:
      - obsidian
    dir: .
  prepublish:
    cmds:
      - uv export --format pylock.toml > ./pylock.toml
      - uv export --format requirements.txt > ./requirements.txt
