# https://taskfile.dev

version: '3'


vars:
  IS_VIRTUAL_CONTAINER: false

tasks:
  playground:
    cmds:
      - uv run python -m notebook
  publicurl:
    cmds:
      - gh repo view --json url | python3 .craft/toolkit/py-shell-pipe-json.py url
  publicname:
    cmds:
      - gh repo view --json name | python3 .craft/toolkit/py-shell-pipe-json.py name
  default:
    cmds:
      - task open-project
      - task open-notes
    silent: true
  sync-notes:
    cmds:
      - git fetch
  open-project:
    cmds:
      - codium .
    dir: .
  open-notes:
    cmds:
      - obsidian .
    dir: .
  preadmit:
    cmds:
      - uv run ruff check
  rdddat:
    cmds:
      - sh .craft/toolkit/rdddat-document-printer.sh > .craft/notes/rdddat.md
    silent: false
  prepublish:
    cmds:
      - sh .craft/toolkit/wiki-home-print.sh > ./.docs/Home.md
      - task rdddat
      - sh .craft/toolkit/submodule-upgrading.sh
      - git add .
      - git commit -m "quick assertion of routine procedures before new version"
      - sh .craft/toolkit/prepublication-routines.sh
      - sh .craft/toolkit/version-shifter.sh
  postpublish:
    cmds:
      - gh repo view --web


      