# https://taskfile.dev

version: '3'

vars:
  IS_VIRTUAL_CONTAINER: false

tasks:
  default:
    cmds:
      - task open-project
      - task 
    silent: true
  sync-notes:
    cmds:
      - git fetch
  open-project:
    cmds:
      - codium 
    dir: .
  open-notes:
    cmds:
      - obsidian
    dir: .
  rdddat:
    cmds:
      - sh toolscripts/rdddat-document-printer.sh > ./.docs/rdddat.md
    silent: false
  prepublish:
    cmds:
      - task rdddat
      - sh toolscripts/submodule-upgrading.sh
      - git add .
      - git commit -m "quick assertion of routine procedures before new version"
      - sh toolscripts/prepublication-routines.sh
  postpublish:
    cmds:
      - gh repo view --web
      

      